import type { Metadata } from 'next';
import './globals.css';

import localFont from 'next/font/local';

const pencilFont = localFont({
  src: './fonts/Hakgyoansim Geurimilgi TTF R.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full">
      <body className={`mx-auto w-96 h-full ${pencilFont.className}`}>
        {children}
      </body>
    </html>
  );
}
