import type { Metadata } from 'next';
import './globals.css';
import LoginBar from './components/LoginBar';
import BottomNavigation from './components/BottomNavigation';
import localFont from 'next/font/local';

const pencilFont = localFont({
  src: './fonts/Hakgyoansim Geurimilgi TTF R.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="h-full">
      <body className={`mx-auto w-96 h-full ${pencilFont.className}`}>
        <div className="h-dvh flex flex-col justify-between bg-yellow-50">
          <div className=" p-6 pt-8 overflow-y-hidden">
            <LoginBar />
            {children}
          </div>
          <BottomNavigation />
        </div>
      </body>
    </html>
  );
}
