'use client';

// import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { ReactQueryClientProvider } from '@/app/provider/ReactQueryProvider';

const pencilFont = localFont({
  src: './fonts/Hakgyoansim Geurimilgi TTF R.ttf',
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="ko" className="h-full">
        <body
          className={`h-dvh mx-auto w-96 ${pencilFont.className} flex flex-col`}
        >
          {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
